import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header/Header";

const commissioner = localFont({
    src: [
        { path: "./fonts/Commissioner-Regular.woff2", weight: "400" },
        { path: "./fonts/Commissioner-Medium.woff2", weight: "500" },
        { path: "./fonts/Commissioner-Bold.woff2", weight: "700" },
    ],
    variable: "--font-commissioner",
    display: "swap",
});


export const metadata = {
    title: "CrowdFunding",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="fr">
        <body
            className={`${commissioner.variable} font-commissioner bg-lotion antialiased`}>
        <Header/>
        {children}
        </body>
        </html>
    );
}
