import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header/Header";

const commissionerRegular = localFont({
  src: "./fonts/Commissioner-Regular.woff2",
  weight: "400",
});

const commissionerMedium = localFont({
    src: "./fonts/Commissioner-Medium.woff2",
    weight: "500",
});

const commissionerBold = localFont({
    src: "./fonts/Commissioner-Bold.woff2",
    weight: "700",
});


export const metadata = {
  title: "CrowdFunding",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body
        className="bg-lotion antialiased font-commissionerRegular"
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
